default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  encoding: unicode

development:
  <<: *default
  database: ecommerce_dev

test:
  <<: *default
  database: ecommerce_qa

production:
  <<: *default
  database: ecommerce_prod
